name: sample_chat_app
description: Sample firebase chat app

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^4.0.1
  logger: ^1.1.0
  recase: ^4.0.0
  equatable: ^2.0.3
  injectable: ^1.5.3
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  sizer: ^2.0.15
  mask_text_input_formatter: ^2.3.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^3.1.0
  flutter_spinkit: ^5.1.0
  firebase_core: ^1.17.1
  flex_color_scheme: ^5.0.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  cloud_functions: ^3.2.16
  google_sign_in: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  auto_route_generator: ^4.0.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/country_codes.json

