// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXRg97c31VMj2sDNLofuYHIR35Cl3r-kc',
    appId: '1:1036405825660:web:d67c7c90512349b05ee9f9',
    messagingSenderId: '1036405825660',
    projectId: 'sample-chat-app-7af69',
    authDomain: 'sample-chat-app-7af69.firebaseapp.com',
    storageBucket: 'sample-chat-app-7af69.appspot.com',
    measurementId: 'G-M54HCP7T3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-m1-sVnB7qm8AYFmBhLPVhPxevlg0Uoc',
    appId: '1:1036405825660:android:13db4dc0485deaac5ee9f9',
    messagingSenderId: '1036405825660',
    projectId: 'sample-chat-app-7af69',
    storageBucket: 'sample-chat-app-7af69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7sJ_FCsB9Y-T95BZJ1z9CV0oCs-Px0fo',
    appId: '1:1036405825660:ios:f7379a7a5d83e1735ee9f9',
    messagingSenderId: '1036405825660',
    projectId: 'sample-chat-app-7af69',
    storageBucket: 'sample-chat-app-7af69.appspot.com',
    iosClientId: '1036405825660-mj07i7sau3130afpjcckpo25h9mmoess.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleChatApp',
  );
}
